services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./backend/Datasets:/app/Datasets
    depends_on:
      - db
    networks:
      - app_network
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    networks:
      - app_network
    restart: always

  db:
    build:
      context: ./db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Newstrongpassword123"
      MSSQL_PID: "Express"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  mssql_data:
