FROM mcr.microsoft.com/mssql/server:2019-latest

# Install sqlcmd and dependencies
USER root
RUN apt-get update && apt-get install -y curl gnupg apt-transport-https \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev \
    && apt-get clean

ENV PATH="$PATH:/opt/mssql-tools/bin"

USER mssql
